name: Web Build & Deploy PROD
on:
  push:
    branches:
      - main
    paths:
      - '.deploy/web/**'
      - '.github/workflows/**'
      - 'apps/web/**'
      - 'package.json'
      - 'yarn.lock'

jobs:
  deploy:
    runs-on: ubuntu-latest    

    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: |
          yarn install

      - name: Build Web
        run: |
          yarn build:web

      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Required
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional
          GITHUB_DEPLOYMENT_ENV: Production
          PRODUCTION: true
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}  #Required
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_PROJECT_ID}} #Required
          WORKING_DIRECTORY: ./

