name: Web Build Before Merge
on:
  pull_request:
    types:
      - opened
      - edited
    paths:
      - '.deploy/web/**'
      - '.github/workflows/**'
      - 'apps/web/**'
      - 'package.json'
      - 'yarn.lock'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: |
          yarn install

      - name: Build Web
        run: |
          yarn build:web
