name: Website Build & Deploy PROD
on:
  push:
    branches:
      - main
    paths:
      - '.deploy/website/**'
      - '.github/workflows/**'
      - 'apps/website/**'
      - 'package.json'
      - 'yarn.lock'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: "yarn"

      - name: Install Packages
        run: |
          yarn install --frozen-lockfile

      - name: Build Website
        run: |
          yarn build:website

      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Required
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional
          GITHUB_DEPLOYMENT_ENV: Production
          PRODUCTION: true
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}  #Required
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEBSITE_PROJECT_ID}} #Required
          WORKING_DIRECTORY: ./
