name: Website Build Before Merge
on:
  pull_request:
    types:
      - opened
      - edited
    paths:
      - '.deploy/website/**'
      - '.github/workflows/**'
      - 'apps/website/**'
      - 'package.json'
      - 'yarn.lock'      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        run: |
          yarn install

      - name: Build Website
        run: |
          yarn build:website
