name: Website Build & Deploy DEV
on:
  push:
    branches:
      - develop
    paths:
      - '.deploy/website/**'
      - '.github/workflows/**'
      - 'apps/website/**'
      - 'package.json'
      - 'yarn.lock'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: |
          yarn install

      - name: Build Website
        run: |
          yarn build:website
      
      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Required
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}  #Required
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_PROJECT_ID}} #Required
          WORKING_DIRECTORY: ./
          ALIAS_DOMAINS: |
            appdev.gauzy.team
